// <auto-generated>
//
// ┌───────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
// │ Provider          │ Microsoft.EntityFrameworkCore.SqlServer                                                                                             │
// ├───────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
// │ Connection String │ Data Source=localhost;Initial Catalog=Chinook_AutoIncrement;User ID=sa;Password=yourStrong(!)Password;Trust Server Certificate=True │
// └───────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
// 
// </auto-generated>

#nullable enable
#pragma warning disable

using System;
using System.Collections.Generic;

namespace Database;

public partial class Album
{
    public int AlbumId { get; set; }

    public string Title { get; set; } = null!;

    public int ArtistId { get; set; }

    public virtual Artist Artist { get; set; } = null!;

    public virtual ICollection<Track> Tracks { get; set; } = new List<Track>();
}
