// <auto-generated>
//
// ┌───────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
// │ Provider          │ Microsoft.EntityFrameworkCore.SqlServer                                                                                             │
// ├───────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
// │ Connection String │ Data Source=localhost;Initial Catalog=Chinook_AutoIncrement;User ID=sa;Password=yourStrong(!)Password;Trust Server Certificate=True │
// └───────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
// 
// </auto-generated>

#nullable enable
#pragma warning disable

using System;
using System.Collections.Generic;

namespace Database;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public string? Company { get; set; }

    public string? Address { get; set; }

    public string? City { get; set; }

    public string? State { get; set; }

    public string? Country { get; set; }

    public string? PostalCode { get; set; }

    public string? Phone { get; set; }

    public string? Fax { get; set; }

    public string Email { get; set; } = null!;

    public int? SupportRepId { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual Employee? SupportRep { get; set; }
}
