// <auto-generated>
//
// ┌───────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
// │ Provider          │ Microsoft.EntityFrameworkCore.SqlServer                                                                                             │
// ├───────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
// │ Connection String │ Data Source=localhost;Initial Catalog=Chinook_AutoIncrement;User ID=sa;Password=yourStrong(!)Password;Trust Server Certificate=True │
// └───────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
// 
// </auto-generated>

#nullable enable
#pragma warning disable

using System;
using System.Collections.Generic;

namespace Database;

public partial class InvoiceLine
{
    public int InvoiceLineId { get; set; }

    public int InvoiceId { get; set; }

    public int TrackId { get; set; }

    public decimal UnitPrice { get; set; }

    public int Quantity { get; set; }

    public virtual Invoice Invoice { get; set; } = null!;

    public virtual Track Track { get; set; } = null!;
}
